= Modern enterprise development with Quarkus
2021-10-20

✓ Hello world in Quarkus
  HTTP GET ...:8080/hello -> hello()
  https://quarkus.io/guides/cdi-reference#simplified-constructor-injection
✓ Difference to Spring & traditional EE
  build-time optimization
✓ Quarkus dev mode, turnaround times
  debug via :5005 (quarkus:dev)
✓ REST, JSON
  JSON-B for declarative mapping
  https://quarkus.io/guides/rest-json
  JSON-P for programmatic mapping
  client, "Rest Client" -> MicroProfile Rest Client or JAX-RS Client
  https://quarkus.io/guides/rest-client
✓ Configuration
  MicroProfile Config, different config sources (application.properties, env, System, ...)
  complex configuration types with @ConfigMapping
  https://blog.sebastian-daschner.com/entries/quarkus-complex-configuration-configmapping
✓ Persistence, transactions, Panache, data migration
  N-1 compatibility
  https://blog.sebastian-daschner.com/entries/flyway-migrate-databases-quarkus
  https://blog.sebastian-daschner.com/entries/flyway-migrate-databases-managed-k8s
✓ CDI, Quarkus-specifics
  Profiles, Events, Qualifiers, Producer Methods
- Concurrency, scheduling
- Instrumentation, metrics, health
- Qute Templating
- Docker, deployment, DevOps aspects
- Quarkus ecosystem
- Project structure / package names
- Native mode vs. JVM mode
- Security, JWT, user auth, OIDC, Keycloak
- Advanced topics
